import { Stage } from '../types';

export const STAGE_ACTIVE_COMPONENTS: Record<Stage, string[]> = {
  [Stage.IF]: ['pc', 'alu-src-a', 'pc-plus4', 'pc0', 'instr-mem', 'ir'],
  [Stage.ID]: ['ir', 'id-decoder', 'control-unit', 'reg-file', 'reg-a', 'reg-b'],
  [Stage.EX]: ['reg-a', 'reg-b', 'alu-src-b', 'alu', 'alu-out'],
  [Stage.MEM]: ['data-mem', 'mdr', 'reg-b', 'alu-out'],
  [Stage.WB]: ['mux-wb', 'reg-file', 'alu-out', 'mdr'],
};

export const STAGE_ACTIVE_WIRES: Record<Stage, string[]> = {
  [Stage.IF]: [
    'pipeline-wire-418-pc-to-instr-mem-addr',
    'pipeline-wire-423-pc-line-to-pc-plus4',
    'pipeline-wire-424-const4-to-pc-plus4',
    'pipeline-wire-426-pc-plus4-to-pc-mux',
    'pipeline-wire-466-pc-mux-to-pc',
    'pipeline-wire-469-instr-mem-ir-to-if-id',
    'pipeline-wire-474-pc4-entry-to-if-id',
    'pipeline-wire-475-pc0-entry-to-if-id',
  ],
  [Stage.ID]: [
    'pipeline-wire-435-if-id-rs1-to-regfile',
    'pipeline-wire-436-if-id-rs2-to-regfile',
    'pipeline-wire-437-if-id-rd-to-id-ex',
    'pipeline-wire-441-if-id-ir-to-control',
    'pipeline-wire-472-if-id-pc4-to-id-ex',
    'pipeline-wire-473-if-id-pc0-to-id-ex',
    'pipeline-wire-491-regfile-rd-b-to-id-ex',
    'pipeline-wire-492-regfile-rd-a-to-id-ex',
    'pipeline-wire-515-control-unit-to-id-ex-control',
    'pipeline-wire-557-if-id-imm-to-imm-gen',
    'pipeline-wire-558-imm-gen-offset-to-id-ex',
  ],
  [Stage.EX]: [
    'pipeline-wire-420-alu-src-b-to-alu-b',
    'pipeline-wire-457-id-ex-imm32-to-alu-src-b',
    'pipeline-wire-493-id-ex-b-to-alu-src-b',
    'pipeline-wire-495-id-ex-pc0-to-branch-adder',
    'pipeline-wire-497-id-ex-imm32-to-branch-adder',
    'pipeline-wire-498-id-ex-rs2-imm-select-to-mux',
    'pipeline-wire-499-id-ex-alu-op-to-alu',
    'pipeline-wire-500-alu-result-to-ex-mem',
    'pipeline-wire-501-id-ex-a-to-alu',
    'pipeline-wire-508-id-ex-imm32-to-ex-mem',
    'pipeline-wire-510-id-ex-bcc-to-branch-logic',
    'pipeline-wire-511-branch-logic-to-branch-target',
    'pipeline-wire-512-alu-flag-to-branch-logic',
    'pipeline-wire-514-alu-branch-flag-to-branch-logic',
    'pipeline-wire-517-id-ex-pc4-to-ex-mem',
    'pipeline-wire-518-branch-adder-output-stub',
    'pipeline-wire-531-id-ex-control-to-ex-mem',
    'pipeline-wire-538-branch-adder-to-branch-logic',
  ],
  [Stage.MEM]: [
    'pipeline-wire-449-ex-mem-b-to-data-mem-write-data',
    'pipeline-wire-453-data-mem-read-to-mem-wb',
    'pipeline-wire-458-ex-mem-alu-result-to-data-mem',
    'pipeline-wire-530-ex-mem-mem-write-to-data-mem',
    'pipeline-wire-543-ex-mem-pc4-to-mem-wb',
  ],
  [Stage.WB]: [
    'pipeline-wire-448-mem-wb-control-to-wb-mux',
    'pipeline-wire-467-mem-wb-alu-result-to-wb-mux',
    'pipeline-wire-507-wb-mux-to-regfile-write-data',
    'pipeline-wire-540-mem-wb-read-data-to-wb-mux',
    'pipeline-wire-541-mem-wb-imm32-to-wb-mux',
    'pipeline-wire-544-mem-wb-pc4-to-wb-mux',
    'pipeline-wire-548-mem-wb-offset-to-wb-mux',
    'pipeline-wire-553-mem-wb-rd-to-regfile-wa',
    'pipeline-wire-554-mem-wb-reg-write-to-regfile',
  ],
};
